### PR TITLE
typo fix and small refactoring

### PR DESCRIPTION
**Pull request by harounchebbi**

### CODE REVIEW

**Comment by TomHAnderson** [comment]
Please also correct the README.md as these paragraphs are the same.

**Comment by harounchebbi** [comment]
Hi Tom,
Did not understand exactly what you mean? I only corrected a typo in the README.md. 
Is there something I've missed?

**Comment by TomHAnderson** [comment]
This page has the exact same wording.  I was hoping you'd put it in your PR too:  https://github.com/mathisGarberg/angular-folder-structure/blob/master/README.md

**Comment by harounchebbi** [comment]
Hi Tom,
Oh Okey I will do this. sorry I misunderstood.

**Pull request closed without merging**
