### PR TITLE
Media directory and documentation

### PR DESCRIPTION
**Pull request by TomHAnderson**
This is a new directory used as the junk drawer for the project.  This is a standard in my projects.  I think it would be a good standard here.

This is the first PR I've made which I consider a standard enhancement to this project and can be accepted or denied.

### CODE REVIEW

**Comment by mathisGarberg** [comment]
Is the `media` directory in any way similar to [this](https://github.com/ngx-rocket/starter-kit/tree/master/docs) directory or am I mistaken?

**Comment by mathisGarberg** [comment]
The idea of the ``media`` directory is to store style guides and other conventions the application should follow ([similar to this](https://github.com/ngx-rocket/starter-kit/tree/master/docs/coding-guides)) or am I mistaken?

**Comment by TomHAnderson** [comment]
The media directory isn't like the starter-kit.  The media directory is used to hold files related to the project such as notes, extra image files, .ai and .pdf files, etc.  It is a storage location only and does not affect how the application runs.

**Comment by mathisGarberg** [comment]
I see. Sounds like a good addition. The purpose is to contain other documents related to the project.

**Pull request merged**
